DROP MODEL chapter7_RegressionMOdel.predict_ticket_price_auto_new;
CREATE MODEL chapter7_RegressionMOdel.predict_ticket_price_auto_new from
chapter7_RegressionModel.sporting_event_ticket_info_training
TARGET final_ticket_price
FUNCTION predict_ticket_price_auto_new
IAM_ROLE default
PROBLEM_TYPE regression
OBJECTIVE 'mse'
SETTINGS (s3_bucket '999999999999-chapter13',
s3_garbage_collect off,
max_runtime 9600);
